name: actions-test
on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sneha Test
        run: make hello && ./hello

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sneha Test
        run: make hello && ./hello
