name: actions-test
on:
  push:

jobs:
  setup:
    uses: actions/checkout@v3

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    needs: setup
      - name: Sneha Test
        run: make hello && ./hello

  mac:
    runs-on: macos-latest
    steps:
    needs: setup
      - name: Sneha Test
        run: make hello && ./hello
