name: actions-test
on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: ubuntu
        run: make hello && ./hello

  mac:
    runs-on: macos-latest
    steps:
      - name: macos
      - uses: actions/checkout@v3
        run: make hello && ./hello
